# Usar una imagen base de Python
FROM python:3.8

# stuff to run the server as a service
USER root
RUN apt-get update
RUN apt-get install -y supervisor nginx nano less curl g++ protobuf-compiler libprotobuf-dev

ENV SERVER_WORKERS=2
ENV SERVER_THREADS=2

# Establecer un directorio de trabajo
#WORKDIR /app

# Copiar los archivos requirements.txt y ejecutar pip install
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

# Copiar el resto del código de la aplicación al contenedor
# COPY . .

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Command to start the application
#CMD ["uvicorn", "App:app", "--host", "0.0.0.0", "--port", "3000"]



